In [2]:
import numpy as np
from sklearn.linear_model import Ridge, Lasso, ElasticNet
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score

In [3]:
X, y = load_diabetes(return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [135]:
ri = Ridge(alpha=0.1)
la = Lasso(alpha=0.1)
en = ElasticNet(alpha=0.1, l1_ratio=0.9)

ri.fit(X_train, y_train)
la.fit(X_train, y_train)
en.fit(X_train, y_train)

y_pred_ri = ri.predict(X_test)
y_pred_la = la.predict(X_test)
y_pred_en = en.predict(X_test)

print(f'R2 Scores : \nRidge:{r2_score(y_test, y_pred_ri)}\nLasso:{r2_score(y_test, y_pred_la)}\nElasticNet:{r2_score(y_test, y_pred_en)}')

R2 Scores : 
Ridge:0.46085219464119265
Lasso:0.4718547867276227
ElasticNet:0.2842543312471031


In [83]:
ri.coef_

array([  42.85566976, -205.49431899,  505.08903304,  317.0932049 ,
       -108.50026183,  -86.23673333, -190.36318008,  151.70708637,
        392.28931896,   79.9081772 ])

In [84]:
la.coef_

array([   0.        , -152.66477923,  552.69777529,  303.36515791,
        -81.36500664,   -0.        , -229.25577639,    0.        ,
        447.91952518,   29.64261704])

In [133]:
en.coef_

array([ 0.40100389,  0.        ,  3.41353382,  2.32614375,  0.4595766 ,
        0.12555225, -1.78311241,  2.12401019,  3.07139136,  1.90618344])

# Elastic Net using SGDRegressor

In [138]:
from sklearn.linear_model import SGDRegressor

sgd = SGDRegressor(penalty='elasticnet', alpha=0.1, l1_ratio=0.9, learning_rate='constant')
sgd.fit(X_train, y_train)

r2_score(y_test, sgd.predict(X_test))

0.2845977377810095